### ISSUE TITLE
ACES workflow support - Caustics support - IES support - 

### ISSUE THREAD

**Issue by AnasFX** [mmp/pbrt-v4#227]
Hi, thank you for the awesome work.
I have a few questions please:
- Is it possible to support the (ACES / ACEScg) workflow, or is it already supported (because pbrt-v4 now is using _spectral rendering_ all the time in its rendering process) ?
- Are (Caustics) supported by default ?
- Is it possible to use an IES file for the lights ?

**Comment by shadeops** [comment]
####  Is it possible to support the (ACES / ACEScg) workflow, or is it already supported (because pbrt-v4 now is using spectral 


Internally the calculations are using spectral rendering. However when specifying rgb input (or output) values you can let pbrt know which colorspace the values are in through the ColorSpace "name" attribute.  Currently srgb (default), dci-p3, rec2020, aces2065-1 are supported. 

You could set your output to be rec2020 or aces2065-1, then using which ever image conversion tool like oiio run it through a full conversion pipeline to whatever output you wanted.

#### Are (Caustics) supported by default ?
Yes but results vary depending on Integrator used, see #228

#### Is it possible to use an IES file for the lights ?
Nope, but there are goniometric lights that you can find further info about here - https://pbrt.org/fileformat-v3#lights

**Comment by AnasFX** [comment]
Thank you very much for the detailed answer. If I have other questions about these three topics I will ask it here if you don't mind, so I don't open another issue for it.
Best Regards
