### ISSUE TITLE
Format specification

### ISSUE THREAD

**Issue by kvark** [mmp/pbrt-v4#235]
How does one parse this scene format? I looked for any sort of specification, and the best I could find is a spec for earlier versions of PBRT plus a diff between them. But a diff is fairly high-level, and it doesn't really count as a spec.
So effectively the [parser code](https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/parser.cpp) is the spec right now, correct?

**Comment by povmaniaco** [comment]
As far I know the scene desciption format is like RnderMan .rib format: https://renderman.pixar.com/resources/RenderMan_20/ribBinding.html

**Comment by mmp** [comment]
@shadeops has written a nice guide to the changes from pbrt-v3 to pbrt-v4: https://github.com/shadeops/pbrt_v3-to-v4_migration.

I have actually (finally!) started work on an update to the pbrt.org website to update all of the documentation for pbrt-v4. I hope to have that done in a week or so.

In the meantime the parser code is effectively the spec (and it is indeed, fairly RIB-inspired in general.)

**Comment by pbrt4bounty** [comment]
I am absolutely looking forward to the publication of the book and really happy to have gotten a really stable GPU build under Windows. To complete the good news, the addon for Blender works better and better.
I am glad that you are updating the documentation since I have some doubts to implement the new materials.
Cheers..

**Comment by mmp** [comment]
Finally: https://www.pbrt.org/fileformat-v4 (!). Possibly also useful: https://www.pbrt.org/users-guide-v4
