### ISSUE TITLE
Interior Mediums and Shape alphas

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#26]
#### Description
When a ray hits a Shape primitive that has an alpha texture (value < 1), should pbrt evaluate the interior medium if one exists?

My first naive assumption was that alpha hit would be the equivalent to a Material "none", but that doesn't seem to be the case [1].

From reading the book [2], it appears the main use case of alpha is for things like leaves. Does it make sense to evaluate an interior medium?

#### Current behavior
Rendered with CPU with https://github.com/mmp/pbrt-v4/tree/8364444
![single_v4](https://user-images.githubusercontent.com/2104033/91680634-ad67a680-eb00-11ea-80d5-c5166ce57a7b.png)

#### Expected behavior
Created by nesting a second slightly smaller shape inside.
![nested_v4](https://user-images.githubusercontent.com/2104033/91680696-e738ad00-eb00-11ea-843e-0b988f74b8c7.png)

#### Scene sources
[pbrt_v4_medium.zip](https://github.com/mmp/pbrt-v4/files/5148200/pbrt_v4_medium.zip)

#### References
[1] https://github.com/mmp/pbrt-v4/blob/8364444d3900ccb7208d56529ef0325af005f9bf/src/pbrt/cpu/primitive.cpp#L48-L84
[2] http://www.pbr-book.org/3ed-2018/Shapes/Triangle_Meshes.html#fragment-Testintersectionagainstalphatextureifpresent-0

**Comment by mmp** [comment]
This is an interesting question; I've been chewing on it a bit...

The way I had been thinking of failing the alpha test was that it essentially meant there was no geometry there after all--the intersection was a no-op, nothing to see here, keep tracing the ray, etc. The potential alternative interpretation, shown in this example, is that there is kind of a pseudo-intersection, but there's no scattering at that point, and then the ray continues doing its thing after(and so in this case, would pick up a new medium, etc.)

I think that both interpretations are reasonable. The current interpretation has the advantage that it can be resolved in the middle of ray intersection testing traversal, while the other would require first resolving what is the closest intersection, then checking alpha, then picking up the new medium and going forth. So I'm inclined to stick with the current interpretation (and document it better), since I think the alternative one would impose some performance cost that wouldn't buy anything in the case where there aren't any participating media involved.

I am of course open to the argument that the alternative is actually better in general here...

**Comment by shadeops** [comment]
I'm in agreement with you, having the more common case being faster is my preference. It only requires a little bit of extra scene assembly to achieve the desired effects above, so imposing a speed penalty to make that extra setup a little easier isn't worth it in my opinion.

Implementing the other interpretation and measuring the performance impact on different types of scenes might make for an interesting exercise for readers. =]

**Comment by mmp** [comment]
Sounds good--thanks! I've made a note about this for discussion and/or exercise-ification in the book.
