### ISSUE TITLE
Questions about Updating pbrt-v3 scenes

### ISSUE THREAD

**Issue by wangxinghao777** [mmp/pbrt-v4#288]
hello, I am having a problem with pbrt -v4, when using the --upgrade command it produces the following.
====
D:\job\Git\pbrt-v4\build\Release>pbrt --upgrade D:\job\Git\pbrt-v4\build\scenes\target0623_3.pbrt > D:\job\Git\pbrt-v4\build\scenes\new.pbrt
Error: D:\job\Git\pbrt-v4\build\scenes\target0623_3.pbrt:16:63: unexpected escaped character "m"
====
what does this error mean?

There is another problem. Converting scenes to pbrt's file format,Using assimp export scene.fbx scene.pbrt will yield
====
D:\job\assimp-3.3.1\build\tools\assimp_cmd\Debug>assimp export D:\job\assimp-3.3.1\build\tools\assimp_cmd\Debug\satellite\target.FBX D:\job\assimp-3.3.1\build\tools\assimp_cmd\Debug\satellite\test.pbrt
assimp export: no output format specified and I failed to guess it
====

**Comment by mmp** [comment]
Characters in strings in pbrt files can be escaped with a slash, e.g. `\n` is a newline and `\"` allows including double quotes without terminating a string. The error is because you apparently have `\m` in a string. (I am guessing in a windows pathname?) You might try using `\\` for backslashes in pathnames or using forward slashes.

I don't know what's going on with assimp; you might try changing to that directory and running `assimp export target.FBX test.pbrt` and see if that makes a difference. Otherwise you should file a bug with assimp.
