### ISSUE TITLE
Got “ERROR Access violation--terminating execution” when using "AreaLights" and "float power" simultaneously

### ISSUE THREAD

**Issue by fitzzc** [mmp/pbrt-v4#293]
Hello, Dr. Pharr~ 
When I was using **AreaLightSource** ,and trying to specify the **"float power"**,  I met the error as the image shown: 
>[ tid 25076 @     0.000s d:\pbrt\pbrt_4\pbrt-v4\src\pbrt\pbrt.cpp:38 ] ERROR Access violation--terminating execution
![image](https://user-images.githubusercontent.com/111592576/186836669-54ead377-ac23-4295-9580-0200e45c9c32.png)

The code I used is as following:
 (**Note:**
 The main code is modified from the *"Example of a pbrt file"* @ *_https://pbrt.org/fileformat-v4#example_*;
And the changed arealight part is coming from the example code of *"Area Lights"* @ *https://pbrt.org/fileformat-v4#area-lights*)

```ruby
LookAt 3 4 1.5  # eye
       .5 .5 0  # look at point
       0 0 1    # up vector
Camera "perspective" "float fov" 45

Sampler "halton" "integer pixelsamples" 128
Integrator "volpath"
Film "rgb" "string filename" "simple_1.png"
     "integer xresolution" [400] "integer yresolution" [400]

WorldBegin

# uniform blue-ish illumination from all directions
LightSource "infinite" "rgb L" [ .4 .45 .5 ]

# The change part begin
AttributeBegin
  AreaLightSource "diffuse" "blackbody L" [ 6500 ] "float power" [ 100 ]
  Translate -3 4 10
  Shape "sphere" "float radius" [ .5 ]
AttributeEnd
# The change part end

AttributeBegin
  Material "dielectric"
  Shape "sphere" "float radius" 1
AttributeEnd

AttributeBegin
  Texture "checks" "spectrum" "checkerboard"
          "float uscale" [16] "float vscale" [16]
          "rgb tex1" [.1 .1 .1] "rgb tex2" [.8 .8 .8]
  Material "diffuse" "texture reflectance" "checks"
  Translate 0 0 -1
  Shape "bilinearmesh"
      "point3 P" [ -20 -20 0   20 -20 0   -20 20 0   20 20 0 ]
      "point2 uv" [ 0 0   1 0    1 1   0 1 ]
AttributeEnd
```

I have found that the error happens as soon as I apply ```"float power" [100] ``` with ```Arealightsouce```.   Why? **Is there anything I missed?**  Do these two parts conflict when used together? :(

**And another question**: About the example code of *"Area Lights"* @ *https://pbrt.org/fileformat-v4#area-lights*:
>What is the meaning of using ```"blackbody L" [ 6500 ] ``` and ```"float power" [ 100 ] ``` simultaneously? In my opinion, we can get the power according to the blackbody if we know the surface area (using E=σT).  
![image](https://user-images.githubusercontent.com/111592576/186839205-89985c88-1508-4f99-8188-511234432371.png)

Thank you for your kind help~ Best wishes!

**Comment by shadeops** [comment]
Nice find! You uncovered a bug.

If no image map was provided and the power argument was used there is a null pointer exception. I made a pull request, #294, to fix this issue.

**Comment by pbrt4bounty** [comment]
I reported this bug quite a long time ago, but in the end I solved it in my local repository.
https://github.com/mmp/pbrt-v4/issues/234

Nice to see that finally is solved in master :)

**Comment by pbrt4bounty** [comment]
Btw.. seems that your patch proposal there may still be an error as 'image' is invoked in the line 924, without first confirming that it has been defined.
`ImageChannelDesc channelDesc = image.GetChannelDesc({"R", "G", "B"});`
 I think the most effective solution is check for image before, in the line 913
`if (phi_v > 0 && image) {`
https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/lights.cpp#L913

Cheers..

**Comment by shadeops** [comment]
Actually that is a good point, in fact I think  is redundant as `channelDesc` isn't even used within the block.
https://github.com/mmp/pbrt-v4/blob/38585b24d1a44c71ac563db9e9c03cc50f5ee553/src/pbrt/lights.cpp#L924-L934

**Comment by pbrt4bounty** [comment]
@shadeops OK I think the problem here, as @fitzzc report, is when you use a 'power' parameter  with a value > 0.0 , without define a image file.
With this `power > 0.0`, this if also true: `if (phi_v > 0){`
..but inside this code block is assumed that `imageColorSpace` is not a nullptr, and for this condition to hold, we also need to hold `if (!filename.empty())` since in that block, it is where it is defined `imageColorSpace`
Also, in this block, `ImageChannelDesc channelDesc = image.GetChannelDesc({"R", "G", "B"});` is called before check if image is something that null. So, you at least need to check for this:
`if (phi_v > 0 && imageColorSpace != nullptr)` or better `if (phi_v > 0 && image && imageColorSpace != nullptr)`
@mmp  What do you think about?
Case apart is if we need a `channelDesc ` defined inside this block..
Cheers..

**Comment by mmp** [comment]
Thanks for the fix @shadeops!

@fitzzc about why power is separate like that: pbrt normalizes blackbody spectra to have a maximum value of 1; otherwise they can be difficult to work with since changing the temperature can wildly change the amount of emitted power. So then the power parameter is necessary to scale the emission spectrum as needed...
