### ISSUE TITLE
Coated Conductor 'g' parameter = 1.0 produce a Nan's and black dots render result

### ISSUE THREAD

**Issue by pbrt4bounty** [mmp/pbrt-v4#333]
It appears that the Coated Conductor material produces incorrect results when the value of 'g' is set to absolute values ​​such as 1.0 or -1.0. The render appears with black dots and many Nan errors on the console. This does not happen when the values ​​are 0.99 or -0.99. 
The guide says about 'g':
```
float texture 'g'  
  Henyey-Greenstein asymmetry parameter ranging from -1 to 1 that describes the distribution of scattered light in the medium
```
Is it perhaps a precision error? I think something similar happened with the 'g' parameter in the 'Subsurface' material.

![imagen](https://user-images.githubusercontent.com/73945652/230773534-50b31ed4-e78f-43e5-a2a9-ad7dffca753e.png)
I can easily set these limits in my addon, but I'm wondering if it's possible to do this in the render engine itself.
Thanks..!

**Comment by pbrt4bounty** [comment]
Seems that I found the place where this value are clamped..
https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/materials.cpp#L385
`Float gg = Clamp(texEval(g, ctx), -1, 1);`
Maybe we should adjust it to `Float gg = Clamp(texEval(g, ctx), -0.999, 0.999);`
@mmp what do tou think?

**Comment by pbrt4bounty** [comment]
Seems that 'thickness' is also involved. Clamp 'g' to 0.99 / -0.99 don't fix the issue. When g = 1.0, the render produce more dots & nan's what the higher the value of 'tickness' is. I need to review my implementation code here.
The scene, in case anyone wants to do some tests.
[thickness_dots.zip](https://github.com/mmp/pbrt-v4/files/11185624/thickness_dots.zip)

**Comment by pbrt4bounty** [comment]
Ok. Seems that my previous comment are incorrect.. This are my conclusions, after some tests with the shared scene:
Up limits for `g`:
When `g` = 1.0, any `thickness` value greater than 0.000004 produces rendering artifacts and NaN console messages
When `g` = 0.999, the render is correct and there are no NaN messages whatever the thickness value.(e.g thickness = 10.0)
Down limits for `g`:
When `g` = -1.0, any `thickness` value greater than 0.000001 produces rendering artifacts and NaN console messages
When `g` = -0.999, any `thickness` value greater than 0.15 produces rendering artifacts and NaN console messages
When `g` = -0.99, the render is correct and there are no NaN messages whatever the `thickness` value.(e.g thickness = 10.0)

According to these tests, it IS possible to fix this error, by setting `Float gg = Clamp(texEval(g, ctx), -0.99, 0.99);`
That being said, the result has been obtained by trial and error, using the reference scene. I don't have enough technical knowledge about the shading system implemented in this version of pbrt. Even, it is possible that I are not using these parameters correctly.
I have ready the patch to fix this and I can create a pull request if you, @mmp have not objection.
Cheers..

**Comment by mmp** [comment]
Yep, Henyey-Greenstein isn't great for |g| \approx 1 which is basically either fully forward scattering or fully backward scattering. It's like a BSDF where if you have a perfectly specular surface: you really want a Dirac delta rather than a very smooth microfacet surface.

Anyway, the origin of those NaNs seems to be in the `SampleHenyeyGreenstein` function; here is a graph of what it computes for `cosTheta` as a function of `u[0]` for a `g` close to 1. It turns out that the numerics are unstable for `u[0]` close to 1 in this case.

<img width="593" alt="image" src="https://user-images.githubusercontent.com/102567/233630660-f44e29be-7dc5-4152-91e2-bdb6bc775733.png">

Anyway, I have added some clamping to both the sampling and evaluation code that should fix this. Let me know if you see any more issues.

**Comment by pbrt4bounty** [comment]
All right now.. Thanks Matt.
