### ISSUE TITLE
pmj02bn skipping precomputed sets?

### ISSUE THREAD

**Issue by Andrew-Helmer** [mmp/pbrt-v4#36]
I'm not sure but it looks like the [dimension variable is used to index into the pmj02bn sets](https://github.com/mmp/pbrt-v4/blob/master/src/pbrt/samplers.h#L231), but those are tables of 2D points, so when the dimension gets incremented by 2, it would be skipping the next set without using it? Also the 1D samples don't use the precomputed tables, but they still increment the dimension value, so I think that would also skip unused sets of the precomputed samples.

I apologize if I'm mistaken about this, I haven't tested it, I was just reading the code.

**Comment by mmp** [comment]
Good eye--you are correct about all of that. That is actually intended, though a little ugly / unsatisfying. Here's the story...

Samplers must provide a `StartPixelSample()` method, which takes a pixel, a sample index, and the dimension of the sample vector to start at. Further, they're supposed to be deterministic about the samples that they generate (new in pbrt-v4, but a real help for debugging, since you can re-render a single pixel and know the same computations will happen for it as for the entire image.)

Now, in the GPU path, Samplers aren't persistent, like they are in the CPU renderer. Rather, Samplers are allocated on the stack in kernels that need them, which is currently a) the camera ray generation kernel, and b) the kernel that generates the samples that will be needed for the next path vertex. So the camera ray kernel starts at dimension 0 as usual, but then the other kernel [has to figure out which dimension to start at](https://github.com/mmp/pbrt-v4/blob/3e389bd807a1a11b3023eae6d67fa01668debf6f/src/pbrt/gpu/samples.cpp#L25) for each bounce.

Ok, so on to the pmj sampler. On the CPU, we could maintain a separate index into the pmj tables and only increment it when a 2D sample was taken. On the GPU, we sort of don't know how many PMJ dimensions have been consumed when we start at an arbitrary sample dimension. Hence, the way it's implemented. Although that skips over pmj sample table entries, it is deterministic for a given dimension, and at least it never reuses the same table twice in a row...

(Maybe there is a cleaner solution. That is all admittedly a little hacky, but I don't have a better idea...)

**Comment by Andrew-Helmer** [comment]
Oh that's interesting, I hadn't dug into the GPU implementation much beyond your HPG talk and YouTube video.

I'm probably missing something, but could you change it to pmjInstance = dimension/2, while still incrementing by 2? I think that would be deterministic for a given dimension, and it would skip fewer sample sets, although it would still skip one for every 2 Get1D() calls.

**Comment by mmp** [comment]
Yep, you're right--good point. Fixed now--thanks!
