### ISSUE TITLE
.obj to pbrt conversion

### ISSUE THREAD

**Issue by parishamaheshj18** [mmp/pbrt-v4#360]
It's not actually an issue but could someone please comment on how I can convert my .obj file to .pbrt in version 4? I used to use obj2pbrt in pbrt-V3. but I can't seem to find that implementation in V4. I do see a whole folder of wavefront in V4. 

I am currently trying to use pbrt v3 to convert .obj to pbrt with "obj2pbrt" and then upgrading from v3 to v4 with "pbrt --upgrade scene.pbrt > scene-v4.pbrt". But I just wanted to know if there is another way currently?

**Comment by mmp** [comment]
`obj2pbrt` was retired since it wasn't super robust and didn't handle every detail of the OBJ format. The better option now is to use [assimp](https://assimp-docs.readthedocs.io/en/v5.3.0/), which now has support for pbrt-v4 export. Or your current approach is perfectly reasonable, if a little indirect.
