### ISSUE TITLE
RGB -> spectrum with near-zero RGB color gives near-one values in some wavelengths

### ISSUE THREAD

**Issue by mmp** [mmp/pbrt-v4#82]
Given RGB (0.00010678071, 0, 0.000010491596), the rgb -> spectrum conversion ends up returning values near 1 starting at lambda around 760.

(Repro case in [this commented-out test](https://github.com/mmp/pbrt-v4/blob/65cadf5daf9ac69a3172aafeae9fc87818f920ce/src/pbrt/util/color_test.cpp#L82).)

**Comment by wjakob** [comment]
Hi Matt,

let me explain why this kind of behavior is not surprising with the current form of the sigmoid model:

1. Although the color you've specified is very dark, it is also quite saturated in a relative sense. Saturated colors lead to functions with stronger variation, because the reflectance must be targeted to a specific wavelength range.

2. The model from the EG paper is as reduced as it gets, so there are basically just two shapes that can do this: a parabola, or an inverted parabola, that are then mapped through the sigmoid. In the case of a parabola, it will become arbitrarily large as you go away from the center, and those values then steadily approach 1.0 after the nonlinearity.

3. The polynomial coefficients are produced by an optimization procedure, so they should of course still be correct. It's important to realize that the CIE curves are almost zero after ~730nm, so this optimization isn't penalized if it finds a good fit that reproduces the color and has a high reflectance in wavelengths where that doesn't matter.

4. Completely unrelated to the above points, but perhaps interesting: almost everything that you can measure that is black (especially black paints, pigments, fabrics), etc. will share a very similar behavior. As you get towards ~700-750nm, the spectrum quickly shoots up to the reflectance of a white material (>80% reflectance). It's an annoyance in the case of EPFL's goniophotometer that is in a room wrapped with black fabric to reduce inter-reflection, but this material is actually white in the IR range :-).  More spectrally uniform blackness can be achieved via carbon, e.g. charcoal.

If this sort of thing was a severe issue in some case, then I don't see an easy way out. The 3-parameter sigmoid model is likely too constrained to apply extra regularization (e.g. "let's prefer spectra with an average matching the RGB intensity"), and you'd have to go to higher dimensions. Which kind of breaks the point of this being a drop-in replacement for RGB values.

Anyways, I'm curious how you came across this, and why you consider it a bug. AFAIK it shouldn't make a visual difference in a rendering.

Best,
Wenzel

**Comment by mmp** [comment]
That all makes sense; 4. is particularly interesting!

It came up when rendering this scene, which is a test I put together for the new chromatic media support in the VolPathIntegrator:

![cloud](https://user-images.githubusercontent.com/102567/98970839-43d32380-24c5-11eb-9ed8-49b211c77683.png)

The medium has RGB values that were set by evaluating different noise functions in each RGB channel, which were clamped to [0,1], which is presumably the source of that 0 channel. Now, the interesting thing is that we compute a grid of majorant values for the medium for use in sampling in `UniformGridMediumProvider::GetMaxDensityGrid()`. For each majorant grid cell, it iterates over the grid of RGB values and for each one that contributes, creates an `RGBUnboundedSpectrum` and calls its `MaxValue()` method. ([Here](https://github.com/mmp/pbrt-v4/blob/334bb8a65bd84d1d4b0d44b4437fe0aa6ac086cc/src/pbrt/media.h#L409).)

In spite of that, the SampledSpectrum density returned by the `UniformGridMediumProvider` [here](https://github.com/mmp/pbrt-v4/blob/334bb8a65bd84d1d4b0d44b4437fe0aa6ac086cc/src/pbrt/media.h#L260) was sometimes greater than the supposed maximum density and in turn the majorant was not a majorant and an assertion hit in the integrator since the null scattering coefficient was negative.

I realize just now that the root cause is that if we have two RGB values, `a` and `b`, even if we find their maximum value over all wavelengths via `RGBUnboundedSpectrum::MaxValue()`, then if we linearly interpolate `a` and `b`, then the maximum value over all wavelengths of that RGB expressed as an `RGBUnboundedSpectrum` may well be greater than either of their individual maximum wavelengths. (Which is reasonable given the representation, but unintuitive.) I assume that is the root cause.

For the purposes here, the right thing to do is probably to clamp the interpolated spectral density to the maximum density. Though the results may be quite inaccurate at those wavelengths (I first saw this with a lambda around 750), hopefully it doesn't matter visually given the matching curves...

**Comment by wjakob** [comment]
Just to clarify, are the polynomial coefficients being interpolated? I wouldn't generally recommend that, parts of the space are pretty nonlinear, and you can have slight color shifts. Better to evaluate the color at the 8 neighboring voxels and then trilinearly interpolate the evaluated spectral reflectances. The sigmoid model is designed to be super-cheap to evaluate so that this is not prohibitive. Or did I misunderstand?

**Comment by mmp** [comment]
Nope--the RGBs are interpolated and then converted to the sigmoid model so that spectral samples can be taken.

**Comment by wjakob** [comment]
Then I don't understand how you could get this unexpectedly high density. Shouldn't the bound hold if you know the maxima of all of the individual spectra, and then those are only trilinearly interpolated?

**Comment by mmp** [comment]
It's the RGBs that are interpolated, not the spectra. (So perhaps that should change...)

e.g. given RGB [ 0.21332493 0.04451838 0.0038149846 ], that ends up with a max spectral value 0.36660978.
Given RGB [ 0.046028335 0.056155182 0.07738396 ], that has a max spectral value 0.11439115.

Take the average of those and you get RGB [ 0.12967664 0.050336782 0.040599473 ], which has a max spectral value 0.9767225

**Comment by wjakob** [comment]
Ah, I see. Evaluating the mapping from RGB -> Polynomial coefficients is kind of expensive (quite a bit of unstructured memory traffic from binary search, many loads), so it's better to run the conversion just once on the discretized RGB values in a pre-process, and then interpolate purely in the spectral domain (which requires only the fast mapping from polynomial coeffs + wavelength -> reflectance).

**Comment by mmp** [comment]
Yep. That was tricky previously, since the interpolation was handled by a separate `SampledGrid` class, which just operated on generic types that it assumed it could multiply by scalars, add them together, etc. So storing `RGBUnboundedSpectrum` in there wouldn't have worked, since it doesn't support those operations. 

Between b25c9b1bd4ac2bd9444f72b34a07b8705e38b0c9, which added a callback to convert the in-memory type to a returned type and 5d574c3c5770dda413574c15a8b6aa7bc48b9081, both of which were just pushed, it's switched over to that and all is well.
